# Generated by Django 4.0.7 on 2024-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deacetyl_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('deacetyl_login_approve', models.BooleanField(default=False, null=True)),
                ('deacetyl_team_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deacetylation_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('purity', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('Deacetylation_Method', models.CharField(max_length=100)),
                ('Reaction_Temperature', models.CharField(max_length=100)),
                ('Reaction_Time', models.CharField(max_length=100)),
                ('Degree_Deacetylation', models.CharField(max_length=100)),
                ('Ash_Content', models.CharField(max_length=100)),
            ],
        ),
    ]
