# Generated by Django 4.0.7 on 2024-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral_dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('purity', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('Mineraltype', models.CharField(max_length=100)),
                ('Separation_Method', models.CharField(max_length=100)),
                ('Reagent_Used', models.CharField(max_length=100)),
                ('Reagent_Concentration', models.CharField(max_length=100)),
                ('Separation_Time', models.CharField(max_length=100)),
                ('Energy_Consumption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mineral_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('mineral_login_approve', models.BooleanField(default=False, null=True)),
                ('mineral_team_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
