# Generated by Django 4.0.7 on 2024-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chitosan_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('chitosan_login_approve', models.BooleanField(default=False, null=True)),
                ('chitosan_team_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
    ]
