# Generated by Django 4.0.7 on 2024-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chitosan_Productions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('purity', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('deprotein_report', models.BooleanField(default=False)),
                ('deproteint_report_mng', models.BooleanField(default=False)),
                ('mineral_report', models.BooleanField(default=False)),
                ('mineral_report_c1', models.BooleanField(default=False)),
                ('mineral_report_mng', models.BooleanField(default=False)),
                ('deacetyl_report', models.BooleanField(default=False)),
                ('deacetyl_report_c1', models.BooleanField(default=False)),
                ('deacetyl_report_mng', models.BooleanField(default=False)),
                ('chitosan_method', models.BooleanField(default=False)),
                ('chitosan_report', models.BooleanField(default=False)),
                ('chitosan_encrypt', models.BooleanField(default=False)),
                ('key_sent', models.BooleanField(default=False)),
                ('chitosan_report_mng', models.BooleanField(default=False)),
                ('Shell_Type', models.CharField(max_length=100, null=True)),
                ('Processing_Method', models.CharField(max_length=100, null=True)),
                ('NaOH_Concentration', models.CharField(max_length=100, null=True)),
                ('Treatment_Time', models.CharField(max_length=100, null=True)),
                ('Moisture_Loss', models.CharField(max_length=100, null=True)),
                ('NaOH_Quantity', models.CharField(max_length=100, null=True)),
                ('Mineraltype', models.CharField(max_length=100, null=True)),
                ('Separation_Method', models.CharField(max_length=100, null=True)),
                ('Reagent_Used', models.CharField(max_length=100, null=True)),
                ('Reagent_Concentration', models.CharField(max_length=100, null=True)),
                ('Separation_Time', models.CharField(max_length=100, null=True)),
                ('Energy_Consumption', models.CharField(max_length=100, null=True)),
                ('min_efficiency', models.CharField(max_length=100, null=True)),
                ('Deacetylation_Method', models.CharField(max_length=100, null=True)),
                ('Reaction_Temperature', models.CharField(max_length=100, null=True)),
                ('Reaction_Time', models.CharField(max_length=100, null=True)),
                ('Degree_Deacetylation', models.CharField(max_length=100, null=True)),
                ('Ash_Content', models.CharField(max_length=100, null=True)),
                ('deacetyl_efficiency', models.CharField(max_length=100, null=True)),
                ('chitosan_extract_method', models.CharField(max_length=100, null=True)),
                ('chit_reagent', models.CharField(max_length=100, null=True)),
                ('viscosity', models.CharField(max_length=100, null=True)),
                ('chit_reagent_concentration', models.CharField(max_length=100, null=True)),
                ('chitosan_efficiency', models.CharField(max_length=100, null=True)),
                ('process_time', models.CharField(max_length=100, null=True)),
                ('encryption_key', models.CharField(max_length=100, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('encrypted_chitosan_extract_method', models.TextField(blank=True, null=True)),
                ('encrypted_chit_reagent', models.TextField(blank=True, null=True)),
                ('encrypted_viscosity', models.TextField(blank=True, null=True)),
                ('encrypted_chit_reagent_concentration', models.TextField(blank=True, null=True)),
                ('encrypted_chitosan_efficiency', models.TextField(blank=True, null=True)),
                ('report_path', models.CharField(max_length=500, null=True)),
                ('Image_graph', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
